# Generated by Django 3.2.8 on 2021-10-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hw_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('due_date', models.DateTimeField()),
                ('course', models.CharField(max_length=30)),
                ('submitted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Session_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=30)),
                ('time_limit', models.FloatField()),
                ('selected_assignments', models.JSONField()),
                ('start_time', models.DateTimeField()),
            ],
        ),
    ]
