# Generated by Django 3.2.9 on 2021-11-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_session', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session_data',
            name='time_limit',
        ),
        migrations.AddField(
            model_name='session_data',
            name='time_limit_hours',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='session_data',
            name='time_limit_mins',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='session_data',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
