# Generated by Django 3.2.9 on 2021-11-12 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw_session', '0002_auto_20211111_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session_data',
            name='selected_assignments',
        ),
    ]
