# Generated by Django 3.2.9 on 2021-11-12 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_session', '0003_remove_session_data_selected_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_data',
            name='selected_assignments',
            field=models.JSONField(null=True),
        ),
    ]
