# Generated by Django 3.2.9 on 2021-11-12 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hw_session', '0004_session_data_selected_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='hw_data',
            name='hw_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hw_session.session_data'),
        ),
    ]
