# Generated by Django 3.2.9 on 2021-11-12 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw_session', '0005_hw_data_hw_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hw_data',
            name='hw_session',
        ),
    ]
