# Generated by Django 3.2.9 on 2021-11-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_session', '0009_session_data_goal_accomplished'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_data',
            name='completed_count',
            field=models.IntegerField(null=True),
        ),
    ]
