# Generated by Django 3.2.8 on 2021-11-13 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw_session', '0011_hw_data_loadedat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hw_data',
            old_name='loadedAt',
            new_name='loaded_at',
        ),
    ]
