# Generated by Django 3.2.8 on 2021-11-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_session', '0012_rename_loadedat_hw_data_loaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hw_data',
            name='loaded_at',
            field=models.DateTimeField(null=True),
        ),
    ]
