# Generated by Django 3.2.8 on 2021-11-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_session', '0014_alter_hw_data_loaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hw_data',
            name='submitted',
        ),
        migrations.AddField(
            model_name='hw_data',
            name='is_completed',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='hw_data',
            name='is_selected',
            field=models.BooleanField(null=True),
        ),
    ]
