# Generated by Django 3.2.8 on 2021-11-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_session', '0015_auto_20211122_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hw_data',
            name='course',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hw_data',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='session_data',
            name='goal',
            field=models.CharField(max_length=100),
        ),
    ]
