# Generated by Django 3.2.8 on 2021-11-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_session', '0016_auto_20211122_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_data',
            name='finish_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='session_data',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
