# Generated by Django 3.2.8 on 2021-12-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_session', '0019_alter_session_data_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_data',
            name='start_time',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
