# Generated by Django 3.2.8 on 2021-12-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_session', '0027_alter_session_data_break_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_data',
            name='finish_time',
            field=models.DateTimeField(null=True),
        ),
    ]
