# Generated by Django 3.2.8 on 2021-12-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_session', '0028_alter_session_data_finish_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session_data',
            name='selected_assignments',
        ),
        migrations.AddField(
            model_name='session_data',
            name='selected_assignment_count',
            field=models.IntegerField(null=True),
        ),
    ]
