# Generated by Django 3.2.8 on 2021-12-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_session', '0029_auto_20211207_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_data',
            name='finish_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
